"""empty message

Revision ID: 3ddee2f6d425
Revises: 
Create Date: 2022-06-13 11:04:25.020066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ddee2f6d425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('file', sa.String(length=512), nullable=True))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('post', 'author')
    op.drop_column('post', 'post_pic')
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.String(length=10), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'date_added')
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'email')
    op.drop_column('users', 'full_name')
    op.add_column('post', sa.Column('post_pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_author_fkey', 'post', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'file')
    # ### end Alembic commands ###
